name: GitHub Snake Game

on:
  # Run every day at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

  # Allow manual execution
  workflow_dispatch:

  # Run when pushing to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generate Snake Animation
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: himuucodes
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy generated files
      - name: Deploy Snake Animation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "🐍 Update GitHub Snake Animation [skip ci]"